"""
Pydantic schemas for Sodimac service request/response validation.
"""
from pydantic import BaseModel, Field, HttpUrl
from typing import List, Optional


class ProductUrlRequest(BaseModel):
    """Request model for product URL processing."""
    urls: List[str] = Field(..., description="List of Sodimac product URLs")

    class Config:
        json_schema_extra = {
            "example": {
                "urls": [
                    "https://www.sodimac.com.br/sodimac-br/product/123456/produto-exemplo/123456/",
                    "https://www.sodimac.com.br/sodimac-br/product/789012/outro-produto/789012/"
                ]
            }
        }


class ProductData(BaseModel):
    """Product data extracted from Sodimac."""
    titulo: str = Field(..., description="Product title")
    preco: str = Field(..., description="Product price (highest price)")
    marca: str = Field(default="", description="Product brand/manufacturer")
    ean: str = Field(default="", description="EAN barcode")
    descricao: str = Field(default="", description="Professional product description generated by AI")
    image_urls: List[str] = Field(default_factory=list, description="Product image URLs")
    url_original: str = Field(..., description="Original product URL")
    error: Optional[str] = Field(None, description="Error message if processing failed")

    class Config:
        json_schema_extra = {
            "example": {
                "titulo": "Conjunto Estar Rattan Milan 4pcs",
                "preco": "R$ 1490,00",
                "marca": "Just Home Collection",
                "ean": "7807998084868",
                "descricao": "Este conjunto de móveis para estar oferece elegância e conforto para sua sala...",
                "image_urls": [
                    "https://media.falabella.com/sodimacBR/123456/public"
                ],
                "url_original": "https://www.sodimac.com.br/sodimac-br/product/123456/produto/123456/"
            }
        }


class BatchResponse(BaseModel):
    """Response model for batch processing."""
    products: List[ProductData] = Field(..., description="List of processed products")
    total_products: int = Field(..., description="Total number of products processed")
    excel_download_url: Optional[str] = Field(None, description="URL to download Excel report")

    class Config:
        json_schema_extra = {
            "example": {
                "products": [],
                "total_products": 2,
                "excel_download_url": "/exports/sodimac_produtos_20260206_143022.xlsx"
            }
        }


class ErrorResponse(BaseModel):
    """Error response model."""
    error: str = Field(..., description="Error message")
    details: Optional[str] = Field(None, description="Additional error details")

    class Config:
        json_schema_extra = {
            "example": {
                "error": "Failed to process URLs",
                "details": "Invalid URL format"
            }
        }