steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bd-as-platform', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bd-as-platform']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bd-as-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bd-as-platform'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_USE_SECRET_MANAGER=true,DEBUG=false'
      - '--set-secrets'
      - 'GCP_SERVICE_ACCOUNT_JSON=bd-image-parser-sa-key:latest'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest'

options:
  logging: CLOUD_LOGGING_ONLY