"""
Pydantic schemas for Leroy Merlin service request/response validation.
"""
from pydantic import BaseModel, Field, HttpUrl
from typing import List, Optional


class ProductUrlRequest(BaseModel):
    """Request model for product URL processing."""
    urls: List[str] = Field(..., description="List of Leroy Merlin product URLs")
    
    class Config:
        json_schema_extra = {
            "example": {
                "urls": [
                    "https://www.leroymerlin.com.br/produto-exemplo_123456",
                    "https://www.leroymerlin.com.br/outro-produto_789012"
                ]
            }
        }


class ProductData(BaseModel):
    """Product data extracted from Leroy Merlin."""
    titulo: str = Field(..., description="Product title")
    preco: str = Field(..., description="Product price (highest price)")
    marca: str = Field(default="", description="Product brand/manufacturer")
    ean: str = Field(default="", description="EAN barcode")
    descricao: str = Field(default="", description="Professional product description generated by AI")
    image_urls: List[str] = Field(default_factory=list, description="Product image URLs (1800x1800)")
    url_original: str = Field(..., description="Original product URL")
    error: Optional[str] = Field(None, description="Error message if processing failed")
    
    class Config:
        json_schema_extra = {
            "example": {
                "titulo": "Mangueira com Enrolador de Plástico Parede 12m WAP",
                "preco": "R$ 199,90",
                "marca": "WAP",
                "ean": "7898152416549",
                "descricao": "Esta mangueira com enrolador de parede oferece praticidade e organização para o seu jardim...",
                "image_urls": [
                    "https://cdn.leroymerlin.com.br/products/..._1800x1800.jpg"
                ],
                "url_original": "https://www.leroymerlin.com.br/produto_123456"
            }
        }


class BatchResponse(BaseModel):
    """Response model for batch processing."""
    products: List[ProductData] = Field(..., description="List of processed products")
    total_products: int = Field(..., description="Total number of products processed")
    excel_download_url: Optional[str] = Field(None, description="URL to download Excel report")
    
    class Config:
        json_schema_extra = {
            "example": {
                "products": [],
                "total_products": 2,
                "excel_download_url": "/exports/leroy_produtos_20260206_143022.xlsx"
            }
        }


class ErrorResponse(BaseModel):
    """Error response model."""
    error: str = Field(..., description="Error message")
    details: Optional[str] = Field(None, description="Additional error details")
    
    class Config:
        json_schema_extra = {
            "example": {
                "error": "Failed to process URLs",
                "details": "Invalid URL format"
            }
        }
